import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Branch from '#models/branch'

export default class BranchSeeder extends BaseSeeder {
  static environment = ['development', 'testing', 'production']

  async run() {
    await Branch.createMany([
      {
        userId: 3,
        agencyId: 1,
        name: 'Eclipse NYC',
        location: 'New York, NY',
        phone: '123-456-7890',
        email: 'nyc@eclipse.com',
        address: '123 Manhattan St, New York, NY 10001',
      },
      {
        userId: 3,
        agencyId: 2,
        name: 'Pronto LA',
        location: 'Los Angeles, CA',
        phone: '987-654-3210',
        email: 'la@pronto.com',
        address: '456 Hollywood Blvd, Los Angeles, CA 90028',
      },
      {
        userId: 3,
        agencyId: 3,
        name: 'Globetrotter Miami',
        location: 'Miami, FL',
        phone: '456-123-7890',
        email: 'miami@globetrotter.com',
        address: '789 Ocean Dr, Miami, FL 33139',
      },
      {
        userId: 3,
        agencyId: 4,
        name: 'Sunshine Travel SF',
        location: 'San Francisco, CA',
        phone: '111-222-3333',
        email: 'sf@sunshinetravel.com',
        address: '101 Market St, San Francisco, CA 94103',
      },
      {
        userId: 3,
        agencyId: 5,
        name: 'Adventure Awaits Denver',
        location: 'Denver, CO',
        phone: '444-555-6666',
        email: 'denver@adventureawaits.com',
        address: '202 Broadway St, Denver, CO 80203',
      },
      {
        userId: 3,
        agencyId: 6,
        name: 'Vacation Experts Orlando',
        location: 'Orlando, FL',
        phone: '777-888-9999',
        email: 'orlando@vacationexperts.com',
        address: '303 Theme Park Blvd, Orlando, FL 32819',
      },
      {
        userId: 3,
        agencyId: 7,
        name: 'Paradise Travels Honolulu',
        location: 'Honolulu, HI',
        phone: '101-202-3030',
        email: 'honolulu@paradisetravels.com',
        address: '404 Beach Ave, Honolulu, HI 96815',
      },
      {
        userId: 3,
        agencyId: 8,
        name: 'City Breaks Chicago',
        location: 'Chicago, IL',
        phone: '909-808-7070',
        email: 'chicago@citybreaks.com',
        address: '505 Michigan Ave, Chicago, IL 60611',
      },
      {
        userId: 3,
        agencyId: 9,
        name: 'Eco Travels Seattle',
        location: 'Seattle, WA',
        phone: '404-505-6060',
        email: 'seattle@ecotravels.com',
        address: '606 Pike St, Seattle, WA 98101',
      },
      {
        userId: 3,
        agencyId: 10,
        name: 'Business Travel NYC',
        location: 'New York, NY',
        phone: '303-404-5050',
        email: 'nyc@businesstravel.com',
        address: '707 Wall St, New York, NY 10005',
      },
      {
        userId: 3,
        agencyId: 11,
        name: 'Luxury Getaways Vegas',
        location: 'Las Vegas, NV',
        phone: '202-303-4040',
        email: 'vegas@luxurygetaways.com',
        address: '808 Strip St, Las Vegas, NV 89109',
      },
      {
        userId: 3,
        agencyId: 12,
        name: 'Family Fun San Diego',
        location: 'San Diego, CA',
        phone: '606-707-8080',
        email: 'sandiego@familyfun.com',
        address: '909 Zoo Rd, San Diego, CA 92101',
      },
      {
        userId: 3,
        agencyId: 13,
        name: 'Historic Travels Boston',
        location: 'Boston, MA',
        phone: '505-606-7070',
        email: 'boston@historictravels.com',
        address: '101 Freedom Trail, Boston, MA 02109',
      },
      {
        userId: 3,
        agencyId: 14,
        name: 'Romantic Getaways Paris',
        location: 'Paris, France',
        phone: '404-505-6060',
        email: 'paris@romanticgetaways.com',
        address: '202 Eiffel Tower Ave, Paris, France 75007',
      },
      {
        userId: 3,
        agencyId: 15,
        name: 'Budget Travel Austin',
        location: 'Austin, TX',
        phone: '707-808-9090',
        email: 'austin@budgettravel.com',
        address: '303 Capitol St, Austin, TX 78701',
      },
      {
        userId: 3,
        agencyId: 16,
        name: 'Wildlife Tours Nairobi',
        location: 'Nairobi, Kenya',
        phone: '808-909-1010',
        email: 'nairobi@wildlifetours.com',
        address: '404 Safari Ave, Nairobi, Kenya 00100',
      },
      {
        userId: 3,
        agencyId: 17,
        name: 'Island Hoppers Phuket',
        location: 'Phuket, Thailand',
        phone: '909-101-2020',
        email: 'phuket@islandhoppers.com',
        address: '505 Island Rd, Phuket, Thailand 83000',
      },
      {
        userId: 3,
        agencyId: 18,
        name: 'Snow Adventures Aspen',
        location: 'Aspen, CO',
        phone: '101-202-3030',
        email: 'aspen@snowadventures.com',
        address: '606 Ski St, Aspen, CO 81611',
      },
      {
        userId: 3,
        agencyId: 19,
        name: 'Urban Explorers Tokyo',
        location: 'Tokyo, Japan',
        phone: '202-303-4040',
        email: 'tokyo@urbanexplorers.com',
        address: '707 Shibuya St, Tokyo, Japan 150-0002',
      },
      {
        userId: 3,
        agencyId: 20,
        name: 'Cruise Planners Miami',
        location: 'Miami, FL',
        phone: '303-404-5050',
        email: 'miami@cruiseplanners.com',
        address: '808 Ocean Dr, Miami, FL 33139',
      },
    ])
  }
}
